# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose



services:
  warehouse-db:
    image: postgres:15
    restart: unless-stopped
    user: postgres
    env_file:
      envs/.postgres
    volumes:
      - warehouse-db-volume:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - '5432:5432'
      - '6543:5432'
    healthcheck:
       test: [ 'CMD', 'pg_isready' ]
       interval: 10s
       timeout: 5s
       retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      envs/.django
    depends_on:
      warehouse-db:
        condition: service_healthy

volumes:
  warehouse-db-volume:
