# Generated by Django 5.0.3 on 2024-03-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('item_group', models.CharField(choices=[('G-1', 'Item group 1'), ('G-2', 'Item group 2')], max_length=3)),
                ('item_unit', models.CharField(choices=[('U-1', 'Item unit 1'), ('U-2', 'Item unit 2')], max_length=3)),
                ('quantity', models.IntegerField(default=1)),
                ('price_without_VAT', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=50)),
                ('storage_location', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.TextField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),

            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('unit', models.CharField(choices=[('U-1', 'Item unit 1'), ('U-2', 'Item unit 2')], max_length=3)),
                ('quantity', models.IntegerField(default=1)),
                ('price_without_VAT', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.TextField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('new', 'New'), ('apr', 'Approved'), ('rej', 'Rejected')], default='new', max_length=3)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.goods')),
            ],
        ),
    ]
