# Generated by Django 5.0.3 on 2024-04-25 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_requestrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('item_group', models.CharField(choices=[('G-1', 'Item group 1'), ('G-2', 'Item group 2')], max_length=3)),
                ('unit_of_measurement', models.CharField(choices=[('U-1', 'Item unit 1'), ('U-2', 'Item unit 2')], max_length=3)),
                ('quantity', models.IntegerField(default=1)),
                ('price_without_VAT', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=50)),
                ('storage_location', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.TextField(blank=True, max_length=250)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['item_id'],
            },
        ),
        migrations.RemoveField(
            model_name='requests',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='employee_name',
        ),
        migrations.CreateModel(
            name='LinkedOrder',
            fields=[
                ('linked_order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('unit_of_measurement', models.CharField(choices=[('U-1', 'Item unit 1'), ('U-2', 'Item unit 2')], max_length=3)),
                ('quantity', models.IntegerField(default=1)),
                ('price_without_VAT', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.TextField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('new', 'New'), ('apr', 'Approved'), ('rej', 'Rejected')], default='new', max_length=3)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.item')),
            ],
            options={
                'verbose_name_plural': 'Linked Orders',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_of_measurement', models.CharField(choices=[('U-1', 'Item unit 1'), ('U-2', 'Item unit 2')], max_length=3)),
                ('quantity', models.IntegerField(default=1)),
                ('price_without_VAT', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.TextField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('new', 'New'), ('apr', 'Approved'), ('rej', 'Rejected')], default='new', max_length=3)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.item')),
            ],
            options={
                'verbose_name_plural': 'Requests',
                'ordering': ['item_id'],
            },
        ),
        migrations.DeleteModel(
            name='RequestRow',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
