# Generated by Django 5.0.3 on 2024-05-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_item_remove_requests_item_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_id']},
        ),
    ]
